### ISSUE TITLE
Retrying after error: Invalid status code

### ISSUE THREAD

**Issue by NiR0Lf** [tducasse/go-instabot#35] opened 2019-02-15 10:54 UTC
![image](https://user-images.githubusercontent.com/44731168/52851930-94162980-3117-11e9-8ce7-757d77c31ce3.png)
I tried doing ` go build ` and ` go install ` but it didn't help with problem. I also deleted the ` session ` and ` key ` files which is the time I took the screenshot from. The last error message keeps repeating until the program closes.I only use 1 user login, so there's not multiple account logged in at all.The profile isn't banned either.

**Comment by NiR0Lf** [comment] 2019-02-15 12:43
Also this is the error message before ending the program.
![image](https://user-images.githubusercontent.com/44731168/52857514-b2842100-3127-11e9-8372-a9e22efa2579.png)

**Comment by tducasse** [comment] 2019-02-15 12:48
It's probably because you are treated as a spam, and they are showing you a captcha. Not sure what you can do about that, maybe use it in a less intensive fashion?

**Comment by UN5T48L3** [comment] 2019-02-16 13:11
Same error.

I was using for 1 month but first time i've seen this error.

**Retrying after error: Invalid status code**

**Comment by tducasse** [comment] 2019-02-16 13:48
Instagram has probably changed their rules about spamming, and maybe set up some kind of captcha. Have you tried logging in via the web interface to see if it works?

**Comment by UN5T48L3** [comment] 2019-02-16 14:01
> Instagram has probably changed their rules about spamming, and maybe set up some kind of captcha. Have you tried logging in via the web interface to see if it works?

Yes sir.
I am not familiar with golang very well so I can't figure out what problem is exactly.

**Comment by tducasse** [comment] 2019-02-16 14:02
Well at this point I really think it's instagram and not the script itself...

**Comment by UN5T48L3** [comment] 2019-02-16 14:15
> Well at this point I really think it's instagram and not the script itself...

Yeah. I was very happy with this script. I hope you update when you can.

**Comment by UN5T48L3** [comment] 2019-02-16 15:55
![ekran resmi 2019-02-16 18 53 45](https://user-images.githubusercontent.com/39417235/52902038-47684680-321c-11e9-8545-11092b4941da.png)
I removed but when I'm trying to re-install shows this error.

**Comment by DeV1doR** [comment] 2019-02-17 01:17
Got the same errors, tried to log in via browser and all is fine, maybe something with request headers?

**Comment by tducasse** [comment] 2019-02-17 03:08
I can reproduce the error... No idea what's going on there. I don't have a lot of time these days so if someone wants to have look, that'd be great. It's _probably_ a change in their API or auth scheme?

**Comment by grpaiva** [comment] 2019-02-17 03:18
Same error here. Just installed and it's a new account. That's so unfortunate, the script is great!

**Comment by grpaiva** [comment] 2019-02-17 03:25
Could this be related to the new instagram [GRAPH API]?(https://developers.facebook.com/products/instagram/)

**Comment by tducasse** [comment] 2019-02-17 03:29
I honestly have no idea. I don't think so. I think the whole thing should be migrated to the new version of goinsta, goinsta v2. I originally forked v1 so that I could continue using it, but it's obviously not working anymore, and it will never be maintained, so migrating would be better in the long run

**Comment by ad** [comment] 2019-02-17 14:39
GetUserByID now returns "405 Not Implemented", replace it with GetUserByUsername and Username instead of ID and this problem will be solved

**Comment by grpaiva** [comment] 2019-02-17 15:15
Thanks @ad ! I'm trying here but I think my changes are not being commited to the build. How can I rebuild? Sorry I'm not used to Golang.

**Comment by grpaiva** [comment] 2019-02-17 15:19
> Thanks @ad ! I'm trying here but I think my changes are not being commited to the build. How can I rebuild? Sorry I'm not used to Golang.

Ohh, got it with `go install`

**Comment by UN5T48L3** [comment] 2019-02-17 15:21
> > Thanks @ad ! I'm trying here but I think my changes are not being commited to the build. How can I rebuild? Sorry I'm not used to Golang.
> 
> Ohh, got it with `go install`

Where we need to put go-instabot binary to be able to run go-instabot from why directory?

BTW thanks @ad

**Comment by UN5T48L3** [comment] 2019-02-17 15:27
So problem is solved. Thanks to @ad 

changing line 195 as `posterInfo, err = insta.GetUserByID(image.User.Username)`

**Comment by tducasse** [comment] 2019-02-17 21:59
Thanks guys, just committed the fix. I should really rewrite the whole thing one day!

**Closed by tducasse** 2019-02-17 21:59 UTC

**Comment by Yomonger** [comment] 2020-07-17 06:17
Hey guys... I just encountered the same issue. can somebody help me solve it because it don't really understand anything. @UN5T48L3 @ad
